### ISSUE TITLE
Peer to peer code review - Testing to do list

### ISSUE THREAD

**Issue by amanuelbelete95** [Tshobohwa/To-Do-List#10]
Hey there, @Tshobohwa and @Belden,
You did a great job while developing your project.

## These are a few adjustments you should make to your projects

- Make sure the style linter error is passing before you submit your final review

**Comment by belden** [comment]
Hi @amanuelbelete95 , I think you meant to tag @Munyabelden on this. I'm not involved in this to-do list project at all.
